---
######################################
# Setup docker APT or YUM repository
######################################
- include: setup-apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - docker-install-all
    - docker-install-setup

- include: setup-yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - docker-install-all
    - docker-install-setup
